---
# postgresql is installed via homebrew seperately
homebrew_installed_packages:
  - { name: chromedriver }
  - { name: redis }
  - { name: elasticsearch }
  - { name: elasticsearch@2.4 }
  - { name: rbenv }
  - { name: phantomjs }
  - { name: ssh-copy-id }
  - { name: git }
  - { name: wget }
  - { name: php70 }
  - { name: mysql }
  - { name: graphicsmagick }

homebrew_taps:
  - homebrew/dupes
  - homebrew/versions
  - homebrew/homebrew-php

homebrew_cask_apps:
  - java
  - atom
  - google-chrome

clt_path: /Library/Developer/CommandLineTools

#blogs and inside are private, prompts for GH user and pass
chapman_apps:
  - cascade-assets
  - signage
  - blogs
  - inside

git_email: "kziegler@chapman.edu"
git_name: "Kayla Ziegler"