---
- git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"

- name: Get list of existing repositories.
  command: ls ~/
  register: existing_directories

# private repositories will prompt for Github user and password
- name: Setup Chapman github repositories
  git: 
    #repo: "http://{{ githubuser }}:{{ githubpass }}@github.com/chapmanu/{{ item }}" 
    repo: "http://github.com/chapmanu/{{ item }}"
    dest: "~/{{ item }}"
    accept_hostkey: yes
  with_items: "{{ chapman_apps }}"
  when: item not in existing_directories

# bundle cascade assets
# others are bundled in individual roles
- name: Cascade-Assets | Run bundle install.
  command: bundle install chdir=~/cascade-assets