---
- name: Get list of existing repositories.
  command: ls ~/
  register: existing_directories

- name: Setup Chapman github repositories
  git: 
    #repo: "http://{{ githubuser }}:{{ githubpass }}@github.com/chapmanu/{{ item }}" 
    repo: "http://github.com/chapmanu/{{ item }}"
    dest: "~/{{ item }}"
    accept_hostkey: yes
  with_items: "{{ chapman_apps }}"
  when: item not in existing_directories

- bundler:
    state: present
    chdir: "~/{{ item }}"
  with_items: "{{ chapman_apps }}"
  become: "{{ ansible_user_id }}"