---
- name: Uninstall existing Homebrew.
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/uninstall
    dest: ~/uninstall
    mode: u+rwx
    force: yes
  become: yes

- name: Run uninstall script.
  shell: ./uninstall --force
  become: yes
  become_user: root
  ignore_errors: yes

- name: Remove Homebrew folders.
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ uninstall_homebrew_folders }}"
  become_user: root

- name: Remove existing Command Line Tools installation
  file:
    path: '{{ clt_path }}'
    state: absent
  become: yes