---
# run bundle install
- name: Bundle install gems
  shell: ARCHFLAGS="-arch x86_64" bundle install --path vendor/cache chdir=~/signage

# just creates empty env file
- name: Create .env file
  file:
    path: ~/signage/.env
    state: touch
  become_user: "{{ ansible_user_id }}"

- name: Check for an .env file.
  stat:
    path: "{{ env_path }}"
  register: env_file_path

# env_path is set in /roles/signage-setup/vars/main.yml
- name: Move .env data.
  command: "mv {{ env_path }} ~/signage/.env"
  when: env_file_path.stat.exists

- name: Get databases.
  command: bundle exec rake db:setup chdir=~/signage
